# Generated by Django 3.0.8 on 2020-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_gc_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default=''),
        ),
    ]
