# Generated by Django 3.0.8 on 2020-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201220_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default='0'),
        ),
    ]
